// Engineering colleges by state (AICTE-approved, curated broad list).
// Users can also type "Other" if not listed.
export const STATES = ["Andhra Pradesh", "Karnataka", "Uttar Pradesh"] as const;
export type StateName = (typeof STATES)[number];

export const COLLEGES: Record<StateName, string[]> = {
  "Andhra Pradesh": [
    "IIT Tirupati",
    "IIIT Sri City",
    "NIT Andhra Pradesh (Tadepalligudem)",
    "IIIT Srikakulam (RGUKT)",
    "IIIT Nuzvid (RGUKT)",
    "IIIT R.K. Valley (RGUKT)",
    "IIIT Ongole (RGUKT)",
    "Andhra University College of Engineering, Visakhapatnam",
    "JNTU Kakinada",
    "JNTU Anantapur",
    "GITAM University, Visakhapatnam",
    "GITAM University, Bengaluru Campus",
    "VIT-AP University, Amaravati",
    "SRM University AP, Amaravati",
    "Vignan's Foundation for Science, Technology & Research, Guntur",
    "K L University (KLEF), Vaddeswaram",
    "Sri Venkateswara University College of Engineering, Tirupati",
    "Sree Vidyanikethan Engineering College, Tirupati",
    "Sri Sivani College of Engineering, Srikakulam",
    "Aditya Engineering College, Surampalem",
    "Aditya Institute of Technology and Management, Tekkali",
    "Anits (Anil Neerukonda Institute of Technology & Sciences), Visakhapatnam",
    "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
    "Gayatri Vidya Parishad College of Engineering for Women, Visakhapatnam",
    "Raghu Engineering College, Visakhapatnam",
    "Raghu Institute of Technology, Visakhapatnam",
    "MVGR College of Engineering, Vizianagaram",
    "GMR Institute of Technology, Rajam",
    "Lendi Institute of Engineering and Technology, Vizianagaram",
    "Sanketika Vidya Parishad Engineering College, Visakhapatnam",
    "Vignan's Institute of Information Technology, Visakhapatnam",
    "Sri Vasavi Engineering College, Tadepalligudem",
    "SRKR Engineering College, Bhimavaram",
    "BVC Engineering College, Odalarevu",
    "Godavari Institute of Engineering and Technology, Rajahmundry",
    "PVP Siddhartha Institute of Technology, Vijayawada",
    "VR Siddhartha Engineering College, Vijayawada",
    "Prasad V. Potluri Siddhartha Institute of Technology, Vijayawada",
    "Nannapaneni Venkat Rao College of Engineering, Tenali",
    "Lakireddy Bali Reddy College of Engineering, Mylavaram",
    "R.V.R. & J.C. College of Engineering, Guntur",
    "Bapatla Engineering College, Bapatla",
    "Chalapathi Institute of Engineering and Technology, Guntur",
    "QIS College of Engineering and Technology, Ongole",
    "PACE Institute of Technology & Sciences, Ongole",
    "Narasaraopeta Engineering College, Narasaraopet",
    "Vignan's Lara Institute of Technology & Science, Guntur",
    "Vasireddy Venkatadri Institute of Technology, Guntur",
    "Tirumala Engineering College, Narasaraopet",
    "Kallam Haranadhareddy Institute of Technology, Guntur",
    "Priyadarshini College of Engineering & Technology, Nellore",
    "Narayana Engineering College, Nellore",
    "Audisankara College of Engineering & Technology, Gudur",
    "Sri Venkateswara College of Engineering, Tirupati",
    "Sree Vidyanikethan Institute of Management, Tirupati",
    "Madanapalle Institute of Technology and Science, Madanapalle",
    "SVEC — Sri Venkateswara Engineering College, Suryapet",
    "SITAMS — Sreenivasa Institute of Technology and Management Studies, Chittoor",
    "SVCET — Sri Venkateswara College of Engineering and Technology, Chittoor",
    "AITS — Annamacharya Institute of Technology and Sciences, Rajampet",
    "AITS — Annamacharya Institute of Technology and Sciences, Tirupati",
    "GPREC — G. Pulla Reddy Engineering College, Kurnool",
    "RGMCET — Rajeev Gandhi Memorial College of Engineering and Technology, Nandyal",
    "KSRM College of Engineering, Kadapa",
    "Yogivemana University, Kadapa",
    "Sri Krishnadevaraya University College of Engineering & Technology, Anantapur",
    "JNTUA College of Engineering, Anantapur",
    "JNTUA College of Engineering, Pulivendula",
    "Sree Rama Engineering College, Tirupati",
    "Chadalawada Ramanamma Engineering College, Tirupati",
    "Malineni Lakshmaiah Women's Engineering College, Guntur",
    "St. Ann's College of Engineering and Technology, Chirala",
    "Ramachandra College of Engineering, Eluru",
    "Sasi Institute of Technology and Engineering, Tadepalligudem",
    "Swarnandhra College of Engineering and Technology, Narsapur",
    "Andhra Loyola Institute of Engineering and Technology, Vijayawada",
    "Nova College of Engineering and Technology, Vijayawada",
    "Amrita Sai Institute of Science and Technology, Paritala",
    "NRI Institute of Technology, Vijayawada",
    "NRI Institute of Technology & Sciences, Agiripalli",
    "Dhanekula Institute of Engineering & Technology, Vijayawada",
    "Usha Rama College of Engineering & Technology, Telaprolu",
    "Chirala Engineering College, Chirala",
    "Nimra College of Engineering and Technology, Vijayawada",
    "SISTAM — Sri Sivani Institute of Science, Technology and Management, Srikakulam",
    "Baba Institute of Technology and Sciences, Visakhapatnam",
    "Chaitanya Engineering College, Visakhapatnam",
    "Pydah College of Engineering, Visakhapatnam",
    "Avanthi Institute of Engineering and Technology, Visakhapatnam",
    "Sri Sarathi Institute of Engineering & Technology, Nuzvid",
    "Bapatla Women's Engineering College, Bapatla",
    "St. Peter's Engineering College, Vijayawada",
    "Other",
  ],
  Karnataka: [
    "IIT Dharwad",
    "IIIT Dharwad",
    "IIIT Raichur",
    "NITK Surathkal (National Institute of Technology Karnataka)",
    "IISc Bangalore (Indian Institute of Science)",
    "IIM Bangalore",
    "R.V. College of Engineering, Bengaluru",
    "PES University, Bengaluru",
    "PES University, EC Campus",
    "M.S. Ramaiah Institute of Technology, Bengaluru",
    "BMS College of Engineering, Bengaluru",
    "BMS Institute of Technology & Management, Bengaluru",
    "Dayananda Sagar College of Engineering, Bengaluru",
    "Dayananda Sagar University, Bengaluru",
    "New Horizon College of Engineering, Bengaluru",
    "Sir M. Visvesvaraya Institute of Technology, Bengaluru",
    "JSS Academy of Technical Education, Bengaluru",
    "Nitte Meenakshi Institute of Technology, Bengaluru",
    "REVA University, Bengaluru",
    "Christ (Deemed to be University), Bengaluru",
    "CMR Institute of Technology, Bengaluru",
    "CMR University, Bengaluru",
    "Presidency University, Bengaluru",
    "Alliance University, Bengaluru",
    "Jain (Deemed-to-be University), Bengaluru",
    "The National Institute of Engineering (NIE), Mysuru",
    "Sri Jayachamarajendra College of Engineering (JSS Science and Technology University), Mysuru",
    "Vidyavardhaka College of Engineering, Mysuru",
    "GSSS Institute of Engineering & Technology for Women, Mysuru",
    "Vidya Vardhaka Sangha's Sri Siddhartha Institute of Technology, Tumakuru",
    "Siddaganga Institute of Technology, Tumakuru",
    "Sri Siddhartha Academy of Higher Education, Tumakuru",
    "Basaveshwar Engineering College, Bagalkot",
    "SDM College of Engineering & Technology, Dharwad",
    "KLE Technological University (BVBCET), Hubballi",
    "KLS Gogte Institute of Technology, Belagavi",
    "Jain College of Engineering, Belagavi",
    "Angadi Institute of Technology and Management, Belagavi",
    "Visvesvaraya Technological University, Belagavi",
    "PDA College of Engineering, Kalaburagi",
    "Poojya Doddappa Appa College of Engineering, Kalaburagi",
    "Sharnbasva University, Kalaburagi",
    "Ballari Institute of Technology and Management, Ballari",
    "Rao Bahadur Y. Mahabaleswarappa Engineering College, Ballari",
    "Sri Krishna Institute of Technology, Bengaluru",
    "Cambridge Institute of Technology, Bengaluru",
    "AMC Engineering College, Bengaluru",
    "Acharya Institute of Technology, Bengaluru",
    "Atria Institute of Technology, Bengaluru",
    "East Point College of Engineering and Technology, Bengaluru",
    "Global Academy of Technology, Bengaluru",
    "HKBK College of Engineering, Bengaluru",
    "Jyothy Institute of Technology, Bengaluru",
    "K.S. Institute of Technology, Bengaluru",
    "KLE Society's College of Engineering, Bengaluru",
    "Malnad College of Engineering, Hassan",
    "Manipal Institute of Technology, Manipal",
    "Manipal Academy of Higher Education, Manipal",
    "NMAM Institute of Technology, Nitte",
    "Nitte University, Mangaluru",
    "St. Joseph Engineering College, Mangaluru",
    "Sahyadri College of Engineering and Management, Mangaluru",
    "P.A. College of Engineering, Mangaluru",
    "Canara Engineering College, Mangaluru",
    "Mangalore Institute of Technology and Engineering, Moodabidri",
    "Bearys Institute of Technology, Mangaluru",
    "Yenepoya Institute of Technology, Moodbidri",
    "Alva's Institute of Engineering and Technology, Moodbidri",
    "Shri Madhwa Vadiraja Institute of Technology and Management, Bantakal",
    "GM Institute of Technology, Davangere",
    "Bapuji Institute of Engineering and Technology, Davangere",
    "S.J.M. Institute of Technology, Chitradurga",
    "Government Engineering College, Hassan",
    "Government Engineering College, Haveri",
    "Government Engineering College, Ramanagara",
    "Government Engineering College, Chamarajanagar",
    "University Visvesvaraya College of Engineering, Bengaluru",
    "Bangalore Institute of Technology, Bengaluru",
    "BNM Institute of Technology, Bengaluru",
    "M.V.J. College of Engineering, Bengaluru",
    "Sapthagiri College of Engineering, Bengaluru",
    "T. John Institute of Technology, Bengaluru",
    "The Oxford College of Engineering, Bengaluru",
    "Vemana Institute of Technology, Bengaluru",
    "SJB Institute of Technology, Bengaluru",
    "Nagarjuna College of Engineering and Technology, Bengaluru",
    "R.N.S. Institute of Technology, Bengaluru",
    "Reva Institute of Technology and Management, Bengaluru",
    "Adichunchanagiri Institute of Technology, Chikmagalur",
    "GITAM University, Bengaluru",
    "Amrita School of Engineering, Bengaluru",
    "Christ University Faculty of Engineering, Bengaluru",
    "Other",
  ],
  "Uttar Pradesh": [
    "IIT Kanpur",
    "IIT (BHU) Varanasi",
    "IIIT Allahabad",
    "IIIT Lucknow",
    "MNNIT Allahabad",
    "Aligarh Muslim University, Zakir Hussain College of Engineering",
    "Harcourt Butler Technical University, Kanpur",
    "Institute of Engineering and Technology, Lucknow",
    "Madan Mohan Malaviya University of Technology, Gorakhpur",
    "Kamla Nehru Institute of Technology, Sultanpur",
    "Bundelkhand Institute of Engineering and Technology, Jhansi",
    "UPES — University of Petroleum and Energy Studies (Meerut Extension)",
    "Bennett University, Greater Noida",
    "Shiv Nadar University, Greater Noida",
    "Amity University, Noida",
    "Amity University, Lucknow",
    "Galgotias University, Greater Noida",
    "Galgotias College of Engineering and Technology, Greater Noida",
    "Sharda University, Greater Noida",
    "GL Bajaj Institute of Technology and Management, Greater Noida",
    "IEC Group of Institutions, Greater Noida",
    "IMS Engineering College, Ghaziabad",
    "Ajay Kumar Garg Engineering College, Ghaziabad",
    "ABES Engineering College, Ghaziabad",
    "ABES Institute of Technology, Ghaziabad",
    "Krishna Institute of Engineering and Technology (KIET), Ghaziabad",
    "IMS Ghaziabad — University Courses Campus",
    "Inderprastha Engineering College, Ghaziabad",
    "Raj Kumar Goel Institute of Technology, Ghaziabad",
    "Meerut Institute of Engineering and Technology, Meerut",
    "Meerut Institute of Technology, Meerut",
    "IIMT Group of Colleges, Meerut",
    "Subharti University, Meerut",
    "Bharat Institute of Technology, Meerut",
    "Noida Institute of Engineering and Technology (NIET), Greater Noida",
    "JSS Academy of Technical Education, Noida",
    "Jaypee Institute of Information Technology, Noida",
    "Jaypee University of Information Technology, Anoopshahr",
    "Bennett University School of Engineering, Greater Noida",
    "Delhi Technical Campus (Greater Noida)",
    "Lloyd Institute of Engineering and Technology, Greater Noida",
    "IIMT College of Engineering, Greater Noida",
    "Dr. A.P.J. Abdul Kalam Technical University, Lucknow (AKTU)",
    "Babu Banarasi Das University, Lucknow",
    "Integral University, Lucknow",
    "Shri Ramswaroop Memorial University, Lucknow",
    "Ambalika Institute of Management & Technology, Lucknow",
    "BBD National Institute of Technology & Management, Lucknow",
    "Goel Institute of Technology & Management, Lucknow",
    "Northern India Engineering College, Lucknow",
    "Rameshwaram Institute of Technology & Management, Lucknow",
    "SRMS College of Engineering and Technology, Bareilly",
    "Invertis University, Bareilly",
    "Rohilkhand Institute of Engineering & Technology, Bareilly",
    "Future Institute of Engineering and Technology, Bareilly",
    "Moradabad Institute of Technology, Moradabad",
    "Teerthanker Mahaveer University, Moradabad",
    "IFTM University, Moradabad",
    "College of Engineering Roorkee",
    "IIT Roorkee (Saharanpur Campus)",
    "Shobhit University, Saharanpur",
    "Feroze Gandhi Institute of Engineering & Technology, Raebareli",
    "Rajkiya Engineering College, Ambedkar Nagar",
    "Rajkiya Engineering College, Azamgarh",
    "Rajkiya Engineering College, Banda",
    "Rajkiya Engineering College, Bijnor",
    "Rajkiya Engineering College, Kannauj",
    "Rajkiya Engineering College, Mainpuri",
    "Rajkiya Engineering College, Mainpuri (RECM)",
    "Rajkiya Engineering College, Sonbhadra",
    "Pranveer Singh Institute of Technology, Kanpur",
    "Rama University, Kanpur",
    "University Institute of Engineering and Technology, CSJM University, Kanpur",
    "Naraina Vidya Peeth Engineering & Management Institute, Kanpur",
    "Axis Institute of Technology and Management, Kanpur",
    "PSIT College of Higher Education, Kanpur",
    "Allenhouse Institute of Technology, Kanpur",
    "United Institute of Technology, Allahabad",
    "Shambhunath Institute of Engineering and Technology, Allahabad",
    "United College of Engineering & Research, Allahabad",
    "Institute of Engineering and Rural Technology, Allahabad",
    "Sam Higginbottom University of Agriculture, Technology and Sciences, Allahabad",
    "Motilal Nehru National Institute of Technology (MNNIT), Allahabad",
    "Institute of Technology, Banaras Hindu University (now IIT BHU)",
    "GNIOT (Greater Noida Institute of Technology), Greater Noida",
    "Accurate Institute of Management & Technology, Greater Noida",
    "R.D. Engineering College, Ghaziabad",
    "IIMT University, Meerut",
    "College of Engineering & Rural Technology, Meerut",
    "Sanskriti University, Mathura",
    "GLA University, Mathura",
    "Hindustan College of Science and Technology, Mathura",
    "IIMT College of Engineering, Meerut",
    "Sri Ramswaroop Memorial College of Engineering & Management, Lucknow",
    "Kanpur Institute of Technology, Kanpur",
    "United Institute of Management, Allahabad",
    "Dr. Ambedkar Institute of Technology for Handicapped, Kanpur",
    "Uttar Pradesh Textile Technology Institute, Kanpur",
    "MJP Rohilkhand University, Bareilly",
    "Dr. Ram Manohar Lohia Avadh University, Ayodhya",
    "Chaudhary Charan Singh University, Meerut",
    "Other",
  ],
};

export function graduationYears(): number[] {
  const current = new Date().getFullYear();
  const years: number[] = [];
  for (let y = 2022; y <= Math.max(current + 1, 2026); y++) years.push(y);
  return years;
}
