import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { 
  ClipboardList, Send, Loader2, Search, User, Eye, HeartHandshake, CheckCircle2, TrendingUp, Printer
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Badge } from "./ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "./ui/dialog";
import { ScrollArea } from "./ui/scroll-area";

import { listDetailedFeedbacks, dispatchFeedbackForm, listActiveFeedbackRequests, updateFeedbackRequest, cancelBulkFeedbackRequests, generateAiFeedbackReport } from "@/lib/operations.functions";

export function AdminDetailedFeedbacksView() {
  const qc = useQueryClient();
  const fetchFeedbacks = useServerFn(listDetailedFeedbacks);
  const triggerCampaign = useServerFn(dispatchFeedbackForm);

  const { data: feedbacks, isLoading, refetch } = useQuery({
    queryKey: ["detailed-feedbacks"],
    queryFn: () => fetchFeedbacks(),
  });

  const fetchActiveRequests = useServerFn(listActiveFeedbackRequests);
  const updateRequestFn = useServerFn(updateFeedbackRequest);
  const cancelBulkFn = useServerFn(cancelBulkFeedbackRequests);
  const generateAiReportFn = useServerFn(generateAiFeedbackReport);

  
  const handlePrintPdf = () => {
    const content = document.getElementById("ai-report-content")?.innerHTML;
    if (!content) return;
    const printWindow = window.open("", "", "width=900,height=900");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>AI Feedback Analysis - VyNexa Connect</title>
            <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
            <style>
              @media print {
                body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                table { page-break-inside: avoid; }
              }
            </style>
          </head>
          <body class="bg-white p-10 max-w-4xl mx-auto font-sans">
            <div class="mb-8 border-b border-slate-200 pb-6 flex justify-between items-end">
              <div>
                <h1 class="text-3xl font-black text-slate-900">Master Feedback Analysis</h1>
                <p class="text-slate-500 mt-2 font-medium">Generated by Gemini AI Engine</p>
              </div>
            </div>
            <div class="prose prose-slate max-w-none">
              ${content}
            </div>
            <script>
              setTimeout(() => {
                window.print();
                window.close();
              }, 1200);
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };


  
  const { data: activeRequests = [], refetch: refetchActive } = useQuery({
    queryKey: ["active-feedback-requests"],
    queryFn: () => fetchActiveRequests(),
  });

  const [isDispatching, setIsDispatching] = useState(false);
  const [showDispatchModal, setShowDispatchModal] = useState(false);
  const [targetType, setTargetType] = useState<"all" | "interns" | "employees">("all");
  const [expiryDays, setExpiryDays] = useState(7);
  const [searchQuery, setSearchQuery] = useState("");
  const [viewingFeedback, setViewingFeedback] = useState<any>(null);
  const [showPreviewForm, setShowPreviewForm] = useState(false);
  
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [aiReport, setAiReport] = useState<string | null>(null);
  const [showAiModal, setShowAiModal] = useState(false);

  const handleBulkCancel = async (type: "all" | "interns" | "employees") => {
    try {
      await cancelBulkFn({ data: { targetType: type } });
      toast.success(`Cancelled all active feedback requests for ${type}.`);
      refetchActive();
    } catch (e: any) {
      toast.error(e.message || "Failed to cancel requests.");
    }
  };

  const handleGenerateAiReport = async () => {
    setIsGeneratingAi(true);
    try {
      const res = await generateAiReportFn();
      setAiReport(res.report || null);
      setShowAiModal(true);
      toast.success("AI Report generated successfully!");
    } catch (e: any) {
      toast.error(e.message || "Failed to generate AI report.");
    } finally {
      setIsGeneratingAi(false);
    }
  };

  const handleDispatch = async () => {
    setIsDispatching(true);
    try {
      const res = await triggerCampaign({ data: { targetType, expiryDays } });
      toast.success(`Dispatched master feedback form to ${res.count} members.`);
      setShowDispatchModal(false);
      qc.invalidateQueries({ queryKey: ["detailed-feedbacks"] });
      qc.invalidateQueries({ queryKey: ["active-feedback-requests"] });
    } catch (err: any) {
      toast.error(err.message || "Failed to dispatch feedback form.");
    } finally {
      setIsDispatching(false);
    }
  };

  const filteredFeedbacks = (feedbacks || []).filter((f: any) => {
    const term = searchQuery.toLowerCase();
    return (f.intern_name || f.profiles?.full_name || "").toLowerCase().includes(term) ||
           (f.profiles?.email || "").toLowerCase().includes(term) ||
           (f.domain_track || "").toLowerCase().includes(term);
  });

  // Analytics
  const avgNps = filteredFeedbacks.length ? (filteredFeedbacks.reduce((acc: number, f: any) => acc + (f.nps_score || 0), 0) / filteredFeedbacks.length).toFixed(1) : "N/A";
  const promoterCount = filteredFeedbacks.filter((f: any) => (f.nps_score || 0) >= 9).length;

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 bg-indigo-950 p-6 rounded-2xl border border-indigo-900 shadow-sm text-white">
        <div className="min-w-0 flex-1">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <ClipboardList className="h-6 w-6 text-indigo-400 shrink-0" /> Master Feedback Campaigns
          </h2>
          <p className="text-xs text-indigo-200 mt-1">
            Dispatch the 30-question master feedback form to members and analyze deep organizational metrics and NPS.
          </p>
          <div className="flex items-center gap-4 mt-4">
             <div className="bg-indigo-900/50 rounded-lg px-3 py-1.5 border border-indigo-800/50 flex items-center gap-2">
                <HeartHandshake className="h-4 w-4 text-emerald-400" />
                <span className="text-xs font-medium">Avg NPS: <span className="font-bold">{avgNps}</span></span>
             </div>
             <div className="bg-indigo-900/50 rounded-lg px-3 py-1.5 border border-indigo-800/50 flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-amber-400" />
                <span className="text-xs font-medium">Promoters: <span className="font-bold">{promoterCount}</span></span>
             </div>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <Button
            onClick={handleGenerateAiReport}
            disabled={isGeneratingAi}
            variant="outline"
            className="border-fuchsia-500 text-fuchsia-600 hover:bg-fuchsia-50 hover:text-fuchsia-700 font-bold h-10"
          >
            {isGeneratingAi ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <TrendingUp className="h-4 w-4 mr-2" />}
            AI Analysis
          </Button>
          <Button
            onClick={() => setShowPreviewForm(true)}
            variant="outline"
            className="border-indigo-500 text-indigo-400 hover:bg-indigo-900/50 hover:text-white font-bold h-10"
          >
            <Eye className="h-4 w-4 mr-2" /> Preview Questions
          </Button>
          <Button
            onClick={() => setShowDispatchModal(true)}
            className="bg-indigo-500 hover:bg-indigo-400 text-white font-bold shadow-md h-10"
          >
            <Send className="h-4 w-4 mr-2" /> Dispatch Master Form
          </Button>
        </div>
      </div>

      {activeRequests.length > 0 && (
        <div className="bg-white dark:bg-slate-950 border border-amber-200 rounded-2xl shadow-sm overflow-hidden">
          <div className="p-4 border-b bg-amber-50/50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <h3 className="font-semibold text-amber-900 flex items-center gap-2">
              Active Feedback Requests
              <Badge className="bg-amber-200 text-amber-900">{activeRequests.length}</Badge>
            </h3>
            <div className="flex items-center gap-2 flex-wrap">
               <span className="text-xs font-bold text-amber-700 mr-2">Bulk Cancel:</span>
               <Button onClick={() => handleBulkCancel("interns")} variant="outline" size="sm" className="h-7 text-xs border-rose-200 text-rose-700 hover:bg-rose-50">Interns</Button>
               <Button onClick={() => handleBulkCancel("employees")} variant="outline" size="sm" className="h-7 text-xs border-rose-200 text-rose-700 hover:bg-rose-50">Employees</Button>
               <Button onClick={() => handleBulkCancel("all")} variant="outline" size="sm" className="h-7 text-xs bg-rose-100 border-rose-300 text-rose-800 hover:bg-rose-200 font-bold">Cancel All</Button>
            </div>
          </div>
          <div className="divide-y max-h-[300px] overflow-y-auto">
            {activeRequests.map((r: any) => (
              <div key={r.id} className="p-4 hover:bg-slate-50 flex items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="h-8 w-8 rounded-full bg-slate-100 flex items-center justify-center shrink-0">
                    <User className="h-4 w-4 text-slate-600" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-slate-900">{r.full_name || "Unknown"}</h4>
                    <p className="text-xs text-slate-500">Expires: {r.feedback_popup_expiry ? new Date(r.feedback_popup_expiry).toLocaleDateString() : "Never"}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={async () => {
                    await updateRequestFn({ data: { userId: r.id, action: "extend", expiryDays: 7 } });
                    toast.success("Extended by 7 days.");
                    refetchActive();
                  }} className="h-8 text-xs border-indigo-200 text-indigo-700 hover:bg-indigo-50">
                    +7 Days
                  </Button>
                  <Button variant="outline" size="sm" onClick={async () => {
                    await updateRequestFn({ data: { userId: r.id, action: "cancel" } });
                    toast.success("Request cancelled.");
                    refetchActive();
                  }} className="h-8 text-xs border-rose-200 text-rose-700 hover:bg-rose-50">
                    Cancel
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="bg-white dark:bg-slate-950 border rounded-2xl shadow-sm overflow-hidden">
        <div className="p-4 border-b flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-slate-50/50">
          <h3 className="font-semibold flex items-center gap-2">
            Submitted Feedbacks
            <Badge className="bg-indigo-100 text-indigo-800">{filteredFeedbacks.length}</Badge>
          </h3>
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" />
            <Input
              placeholder="Search by name, email, domain..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-8 h-9 text-xs bg-white"
            />
          </div>
        </div>

        {isLoading ? (
          <div className="p-12 flex flex-col items-center justify-center text-slate-500">
            <Loader2 className="h-8 w-8 animate-spin mb-4 text-indigo-500" />
            <p className="text-sm font-medium">Loading feedback responses...</p>
          </div>
        ) : filteredFeedbacks.length === 0 ? (
          <div className="p-12 text-center flex flex-col items-center">
            <div className="h-12 w-12 rounded-full bg-slate-100 flex items-center justify-center mb-3">
              <ClipboardList className="h-5 w-5 text-slate-400" />
            </div>
            <h4 className="font-semibold text-slate-900">No Responses Found</h4>
            <p className="text-sm text-slate-500 max-w-sm mt-1">No one has submitted a master feedback form yet.</p>
          </div>
        ) : (
          <div className="divide-y max-h-[600px] overflow-y-auto">
            {filteredFeedbacks.map((f: any) => (
              <div key={f.id} className="p-4 hover:bg-slate-50 transition-colors flex items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="h-10 w-10 rounded-full bg-indigo-100 flex items-center justify-center shrink-0">
                    <User className="h-5 w-5 text-indigo-600" />
                  </div>
                  <div>
                    <h4 className="font-bold text-sm text-slate-900">{f.intern_name || f.profiles?.full_name || "Unknown"}</h4>
                    <p className="text-xs text-slate-500">{f.domain_track || f.profiles?.role}</p>
                  </div>
                </div>
                
                <div className="flex items-center gap-6">
                  <div className="hidden sm:block text-right">
                    <p className="text-xs font-bold text-slate-800">NPS Score</p>
                    <div className="flex items-center justify-end gap-1">
                      <span className={`text-lg font-black ${f.nps_score >= 9 ? 'text-emerald-500' : f.nps_score >= 7 ? 'text-amber-500' : 'text-rose-500'}`}>
                        {f.nps_score}/10
                      </span>
                    </div>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => setViewingFeedback(f)} className="shrink-0 h-9">
                    <Eye className="h-4 w-4 mr-2" /> View Details
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Dispatch Modal */}
      <Dialog open={showDispatchModal} onOpenChange={setShowDispatchModal}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Generate Feedback Campaign</DialogTitle>
            <DialogDescription>
              This will trigger a mandatory onscreen popup for the selected users. They will not be able to dismiss it until they submit their feedback.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4 space-y-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700">Target Audience</label>
              <select
                className="w-full h-10 px-3 text-sm rounded-xl border border-slate-200 bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                value={targetType}
                onChange={(e) => setTargetType(e.target.value as any)}
              >
                <option value="all">All Active Members (Interns & Employees)</option>
                <option value="interns">Interns Only</option>
                <option value="employees">Employees Only</option>
              </select>
            </div>
            
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700">Display Duration (Days)</label>
              <select
                className="w-full h-10 px-3 text-sm rounded-xl border border-slate-200 bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                value={expiryDays}
                onChange={(e) => setExpiryDays(parseInt(e.target.value))}
              >
                <option value={1}>1 Day (Urgent)</option>
                <option value={3}>3 Days</option>
                <option value={7}>7 Days (Standard)</option>
                <option value={14}>14 Days</option>
                <option value={30}>30 Days</option>
              </select>
              <p className="text-[10px] text-slate-500 mt-1">
                The form will disappear from their dashboard if not completed within this timeframe.
              </p>
            </div>
            <div className="p-3 bg-indigo-50 border border-indigo-200 rounded-xl flex items-start gap-2">
              <CheckCircle2 className="h-4 w-4 text-indigo-600 mt-0.5 shrink-0" />
              <p className="text-xs text-indigo-800 leading-relaxed">
                Users will receive the new comprehensive 30-question Master Feedback form covering 8 sections.
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setShowDispatchModal(false)}>Cancel</Button>
            <Button onClick={handleDispatch} disabled={isDispatching} className="bg-indigo-600 hover:bg-indigo-700 text-white">
              {isDispatching ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Send className="h-4 w-4 mr-2" />}
              Dispatch Now
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Viewing Modal */}
      <Dialog open={!!viewingFeedback} onOpenChange={(open) => !open && setViewingFeedback(null)}>
        <DialogContent className="max-w-4xl p-0 overflow-hidden">
          {viewingFeedback && (
            <>
              <div className="bg-slate-900 p-6 text-white flex items-center justify-between">
                <div>
                  <DialogTitle className="text-xl">Feedback Details</DialogTitle>
                  <p className="text-sm text-slate-300 mt-1">
                    Submitted by {viewingFeedback.intern_name || viewingFeedback.profiles?.full_name} on {new Date(viewingFeedback.created_at).toLocaleDateString()}
                  </p>
                </div>
                <div className={`h-12 w-12 rounded-2xl flex items-center justify-center text-xl font-black ${viewingFeedback.nps_score >= 9 ? 'bg-emerald-500' : viewingFeedback.nps_score >= 7 ? 'bg-amber-500' : 'bg-rose-500'}`}>
                  {viewingFeedback.nps_score}
                </div>
              </div>
              
              <ScrollArea className="max-h-[70vh] p-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                  
                  {/* Section 1 & 2 */}
                  <div className="space-y-6">
                    <div>
                      <h4 className="text-xs font-black uppercase text-slate-400 tracking-wider mb-3">Context</h4>
                      <div className="space-y-2">
                        <div className="flex justify-between border-b pb-1"><span className="text-sm text-slate-500">Domain</span><span className="text-sm font-medium">{viewingFeedback.domain_track || "N/A"}</span></div>
                        <div className="flex justify-between border-b pb-1"><span className="text-sm text-slate-500">Duration</span><span className="text-sm font-medium">{viewingFeedback.internship_duration || "N/A"}</span></div>
                        <div className="flex justify-between border-b pb-1"><span className="text-sm text-slate-500">Mentorship Checks</span><span className="text-sm font-medium">{viewingFeedback.mentor_checkins || "N/A"}</span></div>
                      </div>
                    </div>

                    <div>
                      <h4 className="text-xs font-black uppercase text-slate-400 tracking-wider mb-3">Ratings (out of 5)</h4>
                      <div className="space-y-2 bg-slate-50 p-4 rounded-xl border">
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Mentor Access</span><span className="text-sm font-bold">{viewingFeedback.mentor_accessibility}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Feedback Quality</span><span className="text-sm font-bold">{viewingFeedback.feedback_quality}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Doubts Resolved</span><span className="text-sm font-bold">{viewingFeedback.doubts_resolved}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Tasks Clarity</span><span className="text-sm font-bold">{viewingFeedback.tasks_clarity}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Tasks Autonomy</span><span className="text-sm font-bold">{viewingFeedback.tasks_autonomy}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Portal Usability</span><span className="text-sm font-bold">{viewingFeedback.portal_usability}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Workload Manageability</span><span className="text-sm font-bold">{viewingFeedback.workload_manageability}/5</span></div>
                        <div className="flex justify-between"><span className="text-sm text-slate-600">Collaboration</span><span className="text-sm font-bold">{viewingFeedback.collaboration}/5</span></div>
                      </div>
                    </div>
                  </div>

                  {/* Text Responses */}
                  <div className="space-y-6">
                    <div>
                      <h4 className="text-xs font-black uppercase text-slate-400 tracking-wider mb-3">Deep Insights</h4>
                      
                      <div className="space-y-4">
                        <div className="bg-indigo-50/50 p-3 rounded-xl border border-indigo-100">
                          <span className="text-xs font-bold text-indigo-800">Biggest Bottleneck</span>
                          <p className="text-sm text-slate-700 mt-1">{viewingFeedback.biggest_bottleneck || "None reported."}</p>
                        </div>
                        <div className="bg-emerald-50/50 p-3 rounded-xl border border-emerald-100">
                          <span className="text-xs font-bold text-emerald-800">Program Change Suggestion</span>
                          <p className="text-sm text-slate-700 mt-1">{viewingFeedback.program_change || "None reported."}</p>
                        </div>
                        <div className="bg-amber-50/50 p-3 rounded-xl border border-amber-100">
                          <span className="text-xs font-bold text-amber-800">Best Project / Tasks</span>
                          <p className="text-sm text-slate-700 mt-1">{viewingFeedback.best_project || "None reported."}</p>
                        </div>
                        <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
                          <span className="text-xs font-bold text-slate-800">Missing Tools</span>
                          <p className="text-sm text-slate-700 mt-1">{viewingFeedback.missing_tools || "None reported."}</p>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 bg-slate-100 p-3 rounded-xl">
                       <span className="text-sm font-bold text-slate-700">Would return?</span>
                       <Badge className="bg-white text-slate-800">{viewingFeedback.return_interest}</Badge>
                    </div>
                  </div>

                </div>
              </ScrollArea>
              
              <div className="p-4 border-t bg-slate-50 flex justify-end">
                <Button onClick={() => setViewingFeedback(null)}>Close</Button>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Preview Master Form Questions */}
      <Dialog open={showPreviewForm} onOpenChange={setShowPreviewForm}>
        <DialogContent className="max-w-3xl p-0 overflow-hidden bg-slate-50">
          <div className="bg-indigo-950 p-6 text-white border-b border-indigo-900 flex items-center justify-between">
            <div>
              <DialogTitle className="text-xl">Master Form Preview</DialogTitle>
              <p className="text-sm text-indigo-300 mt-1">This is exactly what members will see when dispatched.</p>
            </div>
          </div>
          <ScrollArea className="max-h-[70vh] p-6 space-y-8 bg-white">
            <div className="space-y-6">
              <h4 className="font-bold text-indigo-700">Section 1: Demographics & Context (Optional)</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Full Name & Intern ID</li>
                <li>Domain / Track (Dropdown)</li>
                <li>Internship Duration</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 2: Mentorship & Guidance</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Mentor Accessibility & Responsiveness (1-5 Stars)</li>
                <li>Regular 1-on-1s / Check-ins? (Dropdown)</li>
                <li>Constructive & Detailed Feedback (1-5 Stars)</li>
                <li>Timely Resolution of Technical Blockers (1-5 Stars)</li>
                <li>Felt Valued as an Active Contributor (1-5 Stars)</li>
                <li>What is one specific thing your mentor/lead could have done differently? (Text)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 3: Tasks, Projects & Learning Curve</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Clarity of Assigned Tasks & Briefs (1-5 Stars)</li>
                <li>Did task complexity scale reasonably? (Dropdown)</li>
                <li>Creative Autonomy & Ownership (1-5 Stars)</li>
                <li>Which skills did you improve the most? (Text)</li>
                <li>Which specific project delivered the most real-world learning value? (Text)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 4: Resources, Tools & Documentation</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Onboarding & Setup Documentation (1-5 Stars)</li>
                <li>Delays receiving access, APIs, or repo permissions? (Dropdown)</li>
                <li>What tools or references were missing that could have boosted productivity? (Text)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 5: Portal & Platform Experience</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Portal Usability & Speed (1-5 Stars)</li>
                <li>Did you encounter downtime, session errors, or bugs? (Dropdown)</li>
                <li>Which feature/improvement would make the portal significantly better? (Text)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 6: Working Hours, Workload & Flexibility</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Daily Workload Manageability (1-5 Stars)</li>
                <li>Realistic Deadlines & Sprints (1-5 Stars)</li>
                <li>Respect for Personal Boundaries (1-5 Stars)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 7: Team Collaboration & Culture</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Communication Channels Organization (1-5 Stars)</li>
                <li>Collaboration with Team (1-5 Stars)</li>
                <li>Safe Environment for Questions (1-5 Stars)</li>
                <li>How would you describe the overall culture and team spirit in 3 words? (Text)</li>
              </ul>
              <h4 className="font-bold text-indigo-700 pt-4 border-t">Section 8: Career Impact, NPS & Honest Feedback</h4>
              <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                <li>Net Promoter Score (1-10 Scale)</li>
                <li>If offered, would you be interested in returning for an advanced or full-time role? (Dropdown)</li>
                <li>What was the single biggest bottleneck or frustration you faced? (Text)</li>
                <li>If you were running the internship program next cohort, what is the #1 thing you would change? (Text)</li>
              </ul>
            </div>
          </ScrollArea>
          <div className="p-4 border-t bg-slate-50 flex justify-end">
            <Button onClick={() => setShowPreviewForm(false)}>Close Preview</Button>
          </div>
        </DialogContent>
      </Dialog>
      
      {/* AI Analysis Report Modal */}
      <Dialog open={showAiModal} onOpenChange={setShowAiModal}>
        <DialogContent className="max-w-4xl p-0 overflow-hidden bg-slate-50 flex flex-col max-h-[90vh]">
          <div className="bg-fuchsia-950 p-6 text-white border-b border-fuchsia-900 flex items-center justify-between shrink-0">
            <div>
              <DialogTitle className="text-xl flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-fuchsia-400" /> AI Master Feedback Analysis
              </DialogTitle>
              <p className="text-sm text-fuchsia-300 mt-1">Detailed pin-to-pin report generated by Gemini AI.</p>
            </div>
            <Button onClick={handlePrintPdf} variant="outline" className="bg-white/10 hover:bg-white/20 text-white border-white/20 gap-2 font-bold">
              <Printer className="h-4 w-4" /> Export PDF
            </Button>
          </div>
          <div className="flex-1 overflow-y-auto p-8 bg-white" id="ai-report-content">
            <div className="prose prose-sm sm:prose-base max-w-none text-slate-800">
              <ReactMarkdown
                components={{
                  table: ({node, ...props}) => <div className="overflow-x-auto my-6 shadow-sm rounded-xl border border-slate-200"><table className="min-w-full divide-y divide-slate-200 m-0" {...props} /></div>,
                  thead: ({node, ...props}) => <thead className="bg-slate-50" {...props} />,
                  th: ({node, ...props}) => <th className="px-6 py-3 text-left text-xs font-black text-slate-600 uppercase tracking-wider" {...props} />,
                  td: ({node, ...props}) => <td className="px-6 py-4 text-sm text-slate-700 border-b border-slate-100" {...props} />,
                  h1: ({node, ...props}) => <h1 className="text-3xl font-black text-slate-900 mb-6 pb-2 border-b border-slate-200" {...props} />,
                  h2: ({node, ...props}) => <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4 flex items-center gap-2" {...props} />,
                  h3: ({node, ...props}) => <h3 className="text-xl font-bold text-slate-800 mt-6 mb-3" {...props} />,
                  strong: ({node, ...props}) => <strong className="font-black text-indigo-700" {...props} />
                }}
              >
                {aiReport || "No report generated."}
              </ReactMarkdown>
            </div>
          </div>
          <div className="p-4 border-t bg-slate-50 flex justify-end shrink-0">
            <Button onClick={() => setShowAiModal(false)}>Close Report</Button>
          </div>
        </DialogContent>
      </Dialog>

    </div>
  );
}
