/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SecurityCheckRouteImport } from './routes/security-check'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusTokenRouteImport } from './routes/status.$token'
import { Route as AuthInternRouteImport } from './routes/auth/intern'
import { Route as AuthEmployeeRouteImport } from './routes/auth/employee'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedInternRouteImport } from './routes/_authenticated/intern'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin/operations'
import { Route as AuthenticatedAdminEmailCampaignsRouteImport } from './routes/_authenticated/admin/email-campaigns'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCheckRoute = SecurityCheckRouteImport.update({
  id: '/security-check',
  path: '/security-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusTokenRoute = StatusTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => StatusRoute,
} as any)
const AuthInternRoute = AuthInternRouteImport.update({
  id: '/auth/intern',
  path: '/auth/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmployeeRoute = AuthEmployeeRouteImport.update({
  id: '/auth/employee',
  path: '/auth/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternRoute = AuthenticatedInternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailCampaignsRoute =
  AuthenticatedAdminEmailCampaignsRouteImport.update({
    id: '/admin/email-campaigns',
    path: '/admin/email-campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/security-check': typeof SecurityCheckRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/intern': typeof AuthenticatedInternRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/email-campaigns': typeof AuthenticatedAdminEmailCampaignsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/security-check': typeof SecurityCheckRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/intern': typeof AuthenticatedInternRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/email-campaigns': typeof AuthenticatedAdminEmailCampaignsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/careers': typeof CareersRoute
  '/privacy': typeof PrivacyRoute
  '/security-check': typeof SecurityCheckRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/intern': typeof AuthenticatedInternRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/_authenticated/admin/email-campaigns': typeof AuthenticatedAdminEmailCampaignsRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/privacy'
    | '/security-check'
    | '/status'
    | '/terms'
    | '/track'
    | '/verify'
    | '/cms'
    | '/employee'
    | '/intern'
    | '/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/admin/email-campaigns'
    | '/admin/operations'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/privacy'
    | '/security-check'
    | '/status'
    | '/terms'
    | '/track'
    | '/verify'
    | '/cms'
    | '/employee'
    | '/intern'
    | '/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/admin/email-campaigns'
    | '/admin/operations'
    | '/admin/security'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/careers'
    | '/privacy'
    | '/security-check'
    | '/status'
    | '/terms'
    | '/track'
    | '/verify'
    | '/_authenticated/cms'
    | '/_authenticated/employee'
    | '/_authenticated/intern'
    | '/_authenticated/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/_authenticated/admin/email-campaigns'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CareersRoute: typeof CareersRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityCheckRoute: typeof SecurityCheckRoute
  StatusRoute: typeof StatusRouteWithChildren
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  VerifyRoute: typeof VerifyRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthEmployeeRoute: typeof AuthEmployeeRoute
  AuthInternRoute: typeof AuthInternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-check': {
      id: '/security-check'
      path: '/security-check'
      fullPath: '/security-check'
      preLoaderRoute: typeof SecurityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$token': {
      id: '/status/$token'
      path: '/$token'
      fullPath: '/status/$token'
      preLoaderRoute: typeof StatusTokenRouteImport
      parentRoute: typeof StatusRoute
    }
    '/auth/intern': {
      id: '/auth/intern'
      path: '/auth/intern'
      fullPath: '/auth/intern'
      preLoaderRoute: typeof AuthInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/employee': {
      id: '/auth/employee'
      path: '/auth/employee'
      fullPath: '/auth/employee'
      preLoaderRoute: typeof AuthEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intern': {
      id: '/_authenticated/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof AuthenticatedInternRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-campaigns': {
      id: '/_authenticated/admin/email-campaigns'
      path: '/admin/email-campaigns'
      fullPath: '/admin/email-campaigns'
      preLoaderRoute: typeof AuthenticatedAdminEmailCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRoute
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedInternRoute: typeof AuthenticatedInternRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAdminEmailCampaignsRoute: typeof AuthenticatedAdminEmailCampaignsRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCmsRoute: AuthenticatedCmsRoute,
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedInternRoute: AuthenticatedInternRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAdminEmailCampaignsRoute: AuthenticatedAdminEmailCampaignsRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StatusRouteChildren {
  StatusTokenRoute: typeof StatusTokenRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusTokenRoute: StatusTokenRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CareersRoute: CareersRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityCheckRoute: SecurityCheckRoute,
  StatusRoute: StatusRouteWithChildren,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  VerifyRoute: VerifyRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthEmployeeRoute: AuthEmployeeRoute,
  AuthInternRoute: AuthInternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
