/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusTokenRouteImport } from './routes/status.$token'
import { Route as AuthInternRouteImport } from './routes/auth/intern'
import { Route as AuthEmployeeRouteImport } from './routes/auth/employee'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedInternRouteImport } from './routes/_authenticated/intern'
import { Route as AuthenticatedEmployeeRouteImport } from './routes/_authenticated/employee'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin/operations'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusTokenRoute = StatusTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => StatusRoute,
} as any)
const AuthInternRoute = AuthInternRouteImport.update({
  id: '/auth/intern',
  path: '/auth/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmployeeRoute = AuthEmployeeRouteImport.update({
  id: '/auth/employee',
  path: '/auth/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternRoute = AuthenticatedInternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeRoute = AuthenticatedEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/intern': typeof AuthenticatedInternRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/employee': typeof AuthenticatedEmployeeRoute
  '/intern': typeof AuthenticatedInternRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRouteWithChildren
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRoute
  '/_authenticated/employee': typeof AuthenticatedEmployeeRoute
  '/_authenticated/intern': typeof AuthenticatedInternRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/intern': typeof AuthInternRoute
  '/status/$token': typeof StatusTokenRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/track'
    | '/cms'
    | '/employee'
    | '/intern'
    | '/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/admin/operations'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/track'
    | '/cms'
    | '/employee'
    | '/intern'
    | '/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/admin/operations'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/track'
    | '/_authenticated/cms'
    | '/_authenticated/employee'
    | '/_authenticated/intern'
    | '/_authenticated/templates'
    | '/auth/admin'
    | '/auth/employee'
    | '/auth/intern'
    | '/status/$token'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRouteWithChildren
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthEmployeeRoute: typeof AuthEmployeeRoute
  AuthInternRoute: typeof AuthInternRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$token': {
      id: '/status/$token'
      path: '/$token'
      fullPath: '/status/$token'
      preLoaderRoute: typeof StatusTokenRouteImport
      parentRoute: typeof StatusRoute
    }
    '/auth/intern': {
      id: '/auth/intern'
      path: '/auth/intern'
      fullPath: '/auth/intern'
      preLoaderRoute: typeof AuthInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/employee': {
      id: '/auth/employee'
      path: '/auth/employee'
      fullPath: '/auth/employee'
      preLoaderRoute: typeof AuthEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intern': {
      id: '/_authenticated/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof AuthenticatedInternRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee': {
      id: '/_authenticated/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AuthenticatedEmployeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRoute
  AuthenticatedEmployeeRoute: typeof AuthenticatedEmployeeRoute
  AuthenticatedInternRoute: typeof AuthenticatedInternRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCmsRoute: AuthenticatedCmsRoute,
  AuthenticatedEmployeeRoute: AuthenticatedEmployeeRoute,
  AuthenticatedInternRoute: AuthenticatedInternRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StatusRouteChildren {
  StatusTokenRoute: typeof StatusTokenRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusTokenRoute: StatusTokenRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRouteWithChildren,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthEmployeeRoute: AuthEmployeeRoute,
  AuthInternRoute: AuthInternRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
